SYMBOL V=DOT POINTLABEL;

%LET D1=FJC.DQSCZZ0(OBS=20);
%LET D2=FJC.DQSCZZ0(FIRSTOBS=11);
%LET D3=FJC.DQSCZZ0(OBS=20);
%LET D4=FJC.DQSCZZ0(FIRSTOBS=11);
%LET C1=X1-X11;
%LET C2=X1-X11;
%LET C3=X19;
%LET C4=X19;
%LET B1=D;
%LET B2=D;
%LET B3=D;
%LET B4=D;
%LET F1=X2; %LET G1=X1;
%LET F2=X2; %LET G2=X1;
%LET F3=X1; %LET G3=X19;
%LET F4=X1; %LET G4=X19;


%MACRO DRIVER(START,END);
%DO I=1 %TO 4;
  %DO CLUS=&START %TO &END;
   TITLE "DATA=&&D&I MAXC=&CLUS";
   PROC FASTCLUS DATA=&&D&I MAXC=&CLUS OUT=CLUSTERS LIST  DISTANCE;
      VAR &&C&I;
	  ID &&B&I;
   RUN;
   TITLE "DATA=&&D&I PLOT &CLUS CLUSTERS";
   PROC GPLOT DATA=CLUSTERS;
   PLOT D*&&G&I=CLUSTER/CFRAME=PINK;
   RUN;
   PROC G3D DATA=CLUSTERS;
   SCATTER &&F&I*&&G&I=CLUSTER;
   RUN;
  %END;
  %END;
%MEND;


%DRIVER(2,10);





