%LET D1=FJC.XUCPCL1S;
%LET D2=FJC.XUCPCL2S;
%LET C1=X1-X7;
%LET C2=X1-X7;
%LET B1=DATE;
%LET B2=DATE;

%MACRO DRIVER(MAXC);
  %DO I=1 %TO 1;
  %DO LEAST=1 %TO 1;
  %LET K=1;
  %LET N=%SCAN(&MAXC,&K);
  %DO %WHILE(&N NE);
   TITLE "FITTING &&D&I &N CLUSTERS LEAST=&LEAST";
   PROC PRINCOMP DATA=&&D&I OUT=A1;
   VAR &&C&I;
   RUN;
   PROC PRINT DATA=A1;
   ID &&B&I;
   RUN;
   PROC FASTCLUS DATA=A1 MAXC=&N OUT=CLUSTERS LIST LEAST=&LEAST DISTANCE;
      VAR PRIN1 PRIN2;
	  ID &&B&I;
%LET PLOTITOP=GOPTS=CBACK=PINK, COLOR=BLUE, CFRAME=YELLOW;
%PLOTIT(DATA=CLUSTERS, PLOTVARS=PRIN1 DATE,
        LABELVAR=CLUSTER, TYPEVAR=CLUSTER);
%PLOTIT(DATA=CLUSTERS, PLOTVARS=PRIN1 DATE,
        LABELVAR=&&B&I, TYPEVAR=CLUSTER);
RUN;
  %LET K=%EVAL(&K+1);
  %LET N=%SCAN(&MAXC,&K);
  %END;
  %END;
  %END;
%MEND;

%DRIVER(2 3 5 7 9);
