%let d1=fjc.zyncpcl10;
%let d2=fjc.zyncpcl10;
%let d3=fjc.zyncpcl10;
%let d4=fjc.zyncpcl10;
%let d5=fjc.zyncpcl10;
%let d6=fjc.zyncpcl10;
%let d7=fjc.zyncpcl10;
%let d8=fjc.zyncpcl10;
%let y1=x1;
%let y2=x2;
%let y3=x3;
%let y4=x4;
%let y5=x5;
%let y6=x6;
%let y7=x7;
%let y8=x8;
%let x1=date x2 x3 x4 x5 x6 x7 x8;
%let x2=date x1 x3 x4 x5 x6 x7 x8;
%let x3=date x1 x2 x4 x5 x6 x7 x8;
%let x4=date x1 x2 x3 x5 x6 x7 x8;
%let x5=date x1 x2 x3 x4 x6 x7 x8;
%let x6=date x1 x2 x3 x4 x5 x7 x8;
%let x7=date x1 x2 x3 x4 x5 x6 x8;
%let x8=date x1 x2 x3 x4 x5 x6 x7;

%macro autoreg(nlag);
%do i=1 %to 8;
%let k=1;
%let n=%scan(&nlag,&k);
%do %while(&n ne);
data f&i;
set &&d&i;
run;
title "autoreg &&d&i &&y&i nlag=&n";
proc autoreg data=f&i;
model &&y&i=&&x&i/nlag=&n method=yw dw=4 dwprob backstep;
output out=out&i p=p r=r lcl=lcl ucl=ucl pm=pm rm=rm lclm=lm uclm=um;
data g&i;
merge f&i out&i;
run;
proc print data=g&i(keep=date &&y&i p r lcl ucl);
proc gplot data=g&i;
plot &&y&i*date=1 p*date=2 lcl*date=3 ucl*date=3/overlay cframe=pink;
symbol1 v=dot i=none c=red;
symbol2 v=plus i=join c=green;
symbol3 v=none i=join c=blue;
run;
proc gplot data=out&i;
plot r*date/cframe=yellow;
symbol v=dot i=needle c=blue;
run;
%let k=%eval(&k+1);
   %let n=%scan(&nlag,&k);
%end;
%end;
%mend;

%autoreg(10 15 20);


