SYMBOL V=DOT;

%LET D1=FJC.MODECLU4;
%LET D2=FJC.POVERTY;
%LET C1=BIRTH DEATH;
%LET C2=BIRTH DEATH INFANTDEATH;
%LET B1=COUNTRY;
%LET B2=COUNTRY;
%LET B3=T;
%LET B4=T;
%LET F1=DEATH; %LET G1=BIRTH;
%LET F2=DEATH; %LET G2=BIRTH;




%MACRO DRIVER(START,END);
%DO I=1 %TO 2;
  %DO CLUS=&START %TO &END;
   TITLE "DATA=&&D&I MAXC=&CLUS"; 
   PROC FASTCLUS DATA=&&D&I MAXC=&CLUS OUT=CLUSTERS LIST DISTANCE;
      VAR &&C&I;
	  ID &&B&I;
   RUN;
   TITLE "DATA=&&D&I PLOT &CLUS CLUSTERS";
   PROC GPLOT DATA=CLUSTERS;
   PLOT &&F&I*&&G&I=CLUSTER/CFRAME=PINK;
   RUN;
  %END;
  %END;
%MEND;


%DRIVER(2,10);



