*a*;
proc sgplot data=sasuser.nonlin;
   scatter y=y x=x;
title 'Data NONLIN - Y Plotted on Original Scale';
run; 							*ST205s03.sas;
*b*;
proc sgplot data=sasuser.nonlin;
  scatter y=y x=x;
  yaxis  type=log logbase=e;
title 'Data NONLIN - Y Plotted on Log Scale';
run; 							*ST205s03.sas;
*c*;
proc reg data=sasuser.nonlin plots=all;
   model logy=x;
   title 'Regression Model on LogY';
run;							*ST205s03.sas;
*d*;
proc genmod data=sasuser.nonlin plots=stdreschi(xbeta);
   model y=x / dist=normal link=log obstats;
run;
				 				*ST205s03.sas;
