data box;
set data.main_201212;
where sec eq 1;
keep test_group dda: mms: sav: tda: ira: mtg: iln: ind: heq: card: ccs: sec: hhid ;
rename ccs_amt = card_amt;
run;
data box;
set box;
if not dda then dda_amt = .;
if not mms then mms_amt = .;
if not sav then sav_amt = .;
if not tda then tda_amt = .;
if not ira then ira_amt = .;
if not mtg then mtg_amt = .;
if not heq then heq_amt = .;
if not iln then iln_amt = .;
if not sec then sec_amt = .;
if not ind then ind_amt = .;
if not card then card_amt = .;
run;
data box1 ;
set box ;
order = 1;
balance = dda_amt;
output;
order = 2;
balance = mms_amt;
output;
order = 3;
balance = sav_amt;
output;
order = 4;
balance = tda_amt;
output;
order = 5;
balance = ira_amt;
output;
order = 6;
balance = card_amt;
output;
order = 7;
balance = iln_amt;
output;
order = 8;
balance = ind_amt;
output;
order = 9;
balance = sec_amt;
output;
order = 10;
balance = mtg_amt;
output;
order = 11;
balance = heq_amt;
output;
keep order balance test_group hhid;
run;
proc format;
value order 1 = 'Checking' 2 = 'Money Mkt' 3 = 'Savings' 4 = 'Time Dep' 5 = 'IRAs' 6 = 'Credit Card' 7 = 'Dir. Loan' 8 = 'Ind. Loan' 9 = 'Securities' 10= 'Mortgage' 11='Home Equity';
run;
proc sort data=box1;
by hhid;
run;
data box2;
set box1;
select (test_group);
when (1) amt1 = balance;
when (2) amt2 = balance;
when (3) amt3 = balance;
when (4) amt4 = balance;
when (5) amt5 = balance;
when (6) amt6 = balance;
when (7) amt7 = balance;
when (8) amt8 = balance;
when (9) amt9 = balance;
end;
run;
proc sort data=box1(keep=hhid order) out=class nodupkey;
by hhid;
run;
data box2;
merge box2 (in=a) class (in=b);
by hhid;
if a;
run;
proc sort data=box2;
by order;
run;
proc template;
define statgraph test1;
begingraph;
entrytitle "Deposit Products";
layout overlay / yaxisopts=(linearopts=( viewmax =87500 tickvalueformat=dollar12.) label='Balance' labelattrs=(weight=bold)) xaxisopts=( label="Product" labelattrs=(weight=bold) discreteopts=(TICKVALUEFITPOLICY=STAGGER) ) cycleattrs=true ;
boxplot x=order y=amt1 / discreteoffset=-0.4 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="1" legendlabel="Building Their Future";
boxplot x=order y=amt2 / discreteoffset=-0.3 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="2" legendlabel="Mass Affluent no Kids";
boxplot x=order y=amt3 / discreteoffset=-0.2 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="3" legendlabel="Mainstream Families";
boxplot x=order y=amt4 / discreteoffset=-0.1 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="4" legendlabel="Mass Affluent Families";
boxplot x=order y=amt5 / discreteoffset=0 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="5" legendlabel="Mainstream Retired";
boxplot x=order y=amt6 / discreteoffset=0.1 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="6" legendlabel="Mass Affluent Retired";
boxplot x=order y=amt7 / discreteoffset=0.2 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="7" legendlabel="Not Coded";
boxplot x=order y=amt8 / discreteoffset=0.3 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="8" legendlabel="Building Their Future";
boxplot x=order y=amt9 / discreteoffset=0.4 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="9" legendlabel="Mass Affluent Families";
referenceline y=0 / lineattrs=(pattern=dot);
discretelegend "1" "2" "3" "4" "5" "6" "7" "8" "9" / location=outside valign=bottom halign=center across=5;
endlayout;
endgraph;
end;
run;
proc template;
define statgraph balancesx;
begingraph;
entrytitle "Deposit Products";
layout overlay / yaxisopts=(linearopts=( viewmax =87500 tickvalueformat=dollar12.) label='Balance' labelattrs=(weight=bold)) xaxisopts=( label="Product" labelattrs=(weight=bold) discreteopts=(TICKVALUEFITPOLICY=STAGGER) ) cycleattrs=true ;
boxplot x=order y=amt1 / discreteoffset=-0.4 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="1" legendlabel="Building Their Future";
boxplot x=order y=amt2 / discreteoffset=-0.3 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="2" legendlabel="Mass Affluent no Kids";
boxplot x=order y=amt3 / discreteoffset=-0.2 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="3" legendlabel="Mainstream Families";
boxplot x=order y=amt4 / discreteoffset=-0.1 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="4" legendlabel="Mass Affluent Families";
boxplot x=order y=amt5 / discreteoffset=0 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="5" legendlabel="Mainstream Retired";
boxplot x=order y=amt6 / discreteoffset=0.1 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="6" legendlabel="Mass Affluent Retired";
boxplot x=order y=amt7 / discreteoffset=0.2 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="7" legendlabel="Not Coded";
boxplot x=order y=amt8 / discreteoffset=0.3 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="8" legendlabel="Building Their Future";
boxplot x=order y=amt9 / discreteoffset=0.4 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="9" legendlabel="Mass Affluent Families";
referenceline y=0 / lineattrs=(pattern=dot);
discretelegend "1" "2" "3" "4" "5" "6" "7" "8" "9" / location=outside valign=bottom halign=center across=5;
endlayout;
endgraph;
end;
run;
proc template;
define statgraph loans;
begingraph;
entrytitle "Loan Products";
layout overlay / yaxisopts=(linearopts=( viewmax =87500 tickvalueformat=dollar12.) label='Balance' labelattrs=(weight=bold)) xaxisopts=( label="Product" labelattrs=(weight=bold) discreteopts=(TICKVALUEFITPOLICY=STAGGER) ) cycleattrs=true ;
boxplot x=order y=amt1 / discreteoffset=-0.4 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="1" legendlabel="Building Their Future";
boxplot x=order y=amt2 / discreteoffset=-0.3 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="2" legendlabel="Mass Affluent no Kids";
boxplot x=order y=amt3 / discreteoffset=-0.2 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="3" legendlabel="Mainstream Families";
boxplot x=order y=amt4 / discreteoffset=-0.1 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="4" legendlabel="Mass Affluent Families";
boxplot x=order y=amt5 / discreteoffset=0 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="5" legendlabel="Mainstream Retired";
boxplot x=order y=amt6 / discreteoffset=0.1 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="6" legendlabel="Mass Affluent Retired";
boxplot x=order y=amt7 / discreteoffset=0.2 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="7" legendlabel="Not Coded";
boxplot x=order y=amt8 / discreteoffset=0.3 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="8" legendlabel="Building Their Future";
boxplot x=order y=amt9 / discreteoffset=0.4 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="9" legendlabel="Mass Affluent Families";
referenceline y=0 / lineattrs=(pattern=dot);
discretelegend "1" "2" "3" "4" "5" "6" "7" "8" "9" / location=outside valign=bottom halign=center across=5;
endlayout;
endgraph;
end;
run;
proc template;
define statgraph loans;
begingraph;
entrytitle "Loan Products";
layout overlay / yaxisopts=(linearopts=( viewmax =25000 tickvalueformat=dollar12.) label='Balance' labelattrs=(weight=bold)) xaxisopts=( label="Product" labelattrs=(weight=bold) discreteopts=(TICKVALUEFITPOLICY=STAGGER) ) cycleattrs=true ;
boxplot x=order y=amt1 / discreteoffset=-0.4 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="1" legendlabel="Building Their Future";
boxplot x=order y=amt2 / discreteoffset=-0.3 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="2" legendlabel="Mass Affluent no Kids";
boxplot x=order y=amt3 / discreteoffset=-0.2 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="3" legendlabel="Mainstream Families";
boxplot x=order y=amt4 / discreteoffset=-0.1 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="4" legendlabel="Mass Affluent Families";
boxplot x=order y=amt5 / discreteoffset=0 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="5" legendlabel="Mainstream Retired";
boxplot x=order y=amt6 / discreteoffset=0.1 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="6" legendlabel="Mass Affluent Retired";
boxplot x=order y=amt7 / discreteoffset=0.2 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="7" legendlabel="Not Coded";
boxplot x=order y=amt8 / discreteoffset=0.3 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="8" legendlabel="Building Their Future";
boxplot x=order y=amt9 / discreteoffset=0.4 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="9" legendlabel="Mass Affluent Families";
referenceline y=0 / lineattrs=(pattern=dot);
discretelegend "1" "2" "3" "4" "5" "6" "7" "8" "9" / location=outside valign=bottom halign=center across=5;
endlayout;
endgraph;
end;
run;
proc template;
define statgraph other;
begingraph;
entrytitle "";
layout overlay / yaxisopts=(linearopts=( viewmax =200000 tickvalueformat=dollar12.) label='Balance' labelattrs=(weight=bold)) xaxisopts=( label="Product" labelattrs=(weight=bold) discreteopts=(TICKVALUEFITPOLICY=STAGGER) ) cycleattrs=true ;
boxplot x=order y=amt1 / discreteoffset=-0.4 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="1" legendlabel="Building Their Future";
boxplot x=order y=amt2 / discreteoffset=-0.3 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="2" legendlabel="Mass Affluent no Kids";
boxplot x=order y=amt3 / discreteoffset=-0.2 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="3" legendlabel="Mainstream Families";
boxplot x=order y=amt4 / discreteoffset=-0.1 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="4" legendlabel="Mass Affluent Families";
boxplot x=order y=amt5 / discreteoffset=0 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="5" legendlabel="Mainstream Retired";
boxplot x=order y=amt6 / discreteoffset=0.1 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="6" legendlabel="Mass Affluent Retired";
boxplot x=order y=amt7 / discreteoffset=0.2 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="7" legendlabel="Not Coded";
boxplot x=order y=amt8 / discreteoffset=0.3 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="8" legendlabel="Building Their Future";
boxplot x=order y=amt9 / discreteoffset=0.4 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="9" legendlabel="Mass Affluent Families";
referenceline y=0 / lineattrs=(pattern=dot);
discretelegend "1" "2" "3" "4" "5" "6" "7" "8" "9" / location=outside valign=bottom halign=center across=5;
endlayout;
endgraph;
end;
run;
proc template;
define statgraph other;
begingraph;
entrytitle "";
layout overlay / yaxisopts=(linearopts=( viewmax =200000 tickvalueformat=dollar12.) label='Balance' labelattrs=(weight=bold)) xaxisopts=( label="Product" labelattrs=(weight=bold) discreteopts=(TICKVALUEFITPOLICY=STAGGER) ) cycleattrs=true ;
boxplot x=order y=amt1 / discreteoffset=-0.4 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="1" legendlabel="Building Their Future";
boxplot x=order y=amt2 / discreteoffset=-0.3 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="2" legendlabel="Mass Affluent no Kids";
boxplot x=order y=amt3 / discreteoffset=-0.2 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="3" legendlabel="Mainstream Families";
boxplot x=order y=amt4 / discreteoffset=-0.1 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="4" legendlabel="Mass Affluent Families";
boxplot x=order y=amt5 / discreteoffset=0 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="5" legendlabel="Mainstream Retired";
boxplot x=order y=amt6 / discreteoffset=0.1 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="6" legendlabel="Mass Affluent Retired";
boxplot x=order y=amt7 / discreteoffset=0.2 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="7" legendlabel="Not Coded";
boxplot x=order y=amt8 / discreteoffset=0.3 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="8" legendlabel="Building Their Future";
boxplot x=order y=amt9 / discreteoffset=0.4 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="9" legendlabel="Mass Affluent Families";
referenceline y=0 / lineattrs=(pattern=dot);
discretelegend "1" "2" "3" "4" "5" "6" "7" "8" "9" / location=outside valign=bottom halign=center across=5;
endlayout;
endgraph;
end;
run;
proc template;
define statgraph other;
begingraph;
entrytitle "";
layout overlay / yaxisopts=(linearopts=( viewmax =200000 tickvalueformat=dollar12.) label='Balance' labelattrs=(weight=bold)) xaxisopts=( label="Product" labelattrs=(weight=bold) discreteopts=(TICKVALUEFITPOLICY=STAGGER) ) cycleattrs=true ;
boxplot x=order y=amt1 / discreteoffset=-0.4 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="1" legendlabel="Building Their Future";
boxplot x=order y=amt2 / discreteoffset=-0.3 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="2" legendlabel="Mass Affluent no Kids";
boxplot x=order y=amt3 / discreteoffset=-0.2 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="3" legendlabel="Mainstream Families";
boxplot x=order y=amt4 / discreteoffset=-0.1 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="4" legendlabel="Mass Affluent Families";
boxplot x=order y=amt5 / discreteoffset=0 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="5" legendlabel="Mainstream Retired";
boxplot x=order y=amt6 / discreteoffset=0.1 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="6" legendlabel="Mass Affluent Retired";
boxplot x=order y=amt7 / discreteoffset=0.2 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="7" legendlabel="Not Coded";
boxplot x=order y=amt8 / discreteoffset=0.3 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="8" legendlabel="Building Their Future";
boxplot x=order y=amt9 / discreteoffset=0.4 boxwidth=.1 outlierattrs=(color=grey) medianattrs=(color=red) meanattrs=(color=red symbol=DiamondFilled) display=(CAPS FILL MEAN MEDIAN) name="9" legendlabel="Mass Affluent Families";
referenceline y=0 / lineattrs=(pattern=dot);
discretelegend "1" "2" "3" "4" "5" "6" "7" "8" "9" / location=outside valign=bottom halign=center across=5;
endlayout;
endgraph;
end;
run;
