libname myxls oledb init_string="Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Documents and Settings\ewnym5s\My Documents\virtually domiciled\Tran_Segment Analysis_20120720.xls;Extended Properties=Excel 12.0";
data temp_xxx;
length segment_new $25;
set bal3;
segment_new = put(segment, segfmt.);
drop segment;
run;
data myxls.product;
set temp_xxx (rename=(segment_new = segment) where=(segment ne ''));
run;
data temp_xxx;
length segment_new $25 cbr_new $ 25;
set cbr_results;
segment_new = put(segment, segfmt.);
cbr_new = put(cbr, cbr2012fmt.);
drop cbr segment;
run;
data myxls.cbr ;
set temp_xxx (drop=_type_ _page_ _table_ rename=(segment_new = segment cbr_new = cbr) where=(segment ne '' and cbr ne ''));
run;
data temp_xxx;
length segment_new $25 market_new $ 25;
set market_results;
segment_new = put(segment, segfmt.);
market_new = put(market, mkt2012fmt.);
drop market segment;
run;
data myxls.market ;
set temp_xxx (drop=_type_ _page_ _table_ rename=(segment_new = segment market_new = market) where=(segment ne '' and market ne ''));
run;
data temp_xxx;
length segment_new $25 band_new $ 25;
set band_results;
segment_new = put(segment, segfmt.);
band_new = put(band, $2.);
drop band segment;
run;
data myxls.band ;
set temp_xxx (drop=_type_ _page_ _table_ rename=(segment_new = segment band_new = band) where=(segment ne '' and band ne ''));
run;
data temp_xxx;
length segment_new $25 tenure_yr_new $ 25;
set tenure_yr_results;
segment_new = put(segment, segfmt.);
tenure_yr_new = put(tenure_yr, tenureband.);
drop tenure_yr segment;
run;
data myxls.tenure_yr ;
set temp_xxx (drop=_type_ _page_ _table_ rename=(segment_new = segment tenure_yr_new = tenure_yr) where=(segment ne '' and tenure_yr ne ''));
run;
data temp_xxx;
length segment_new $25 svcs_new $ 25;
set svcs_results;
segment_new = put(segment, segfmt.);
svcs_new = put(svcs, comma2.);
drop svcs segment;
run;
data myxls.svcs ;
set temp_xxx (drop=_type_ _page_ _table_ rename=(segment_new = segment svcs_new = svcs) where=(segment ne '' and svcs ne ''));
run;
data temp_xxx;
length segment_new $25 cqi_new $ 25;
set cqi_results;
segment_new = put(segment, segfmt.);
cqi_new = put(cqi, comma2.);
drop cqi segment;
run;
data myxls.cqi ;
set temp_xxx (drop=_type_ _page_ _table_ rename=(segment_new = segment cqi_new = cqi) where=(segment ne '' and cqi ne ''));
run;
data temp_xxx;
length segment_new $25 cqi_dd_new $ 25;
set cqi_dd_results;
segment_new = put(segment, segfmt.);
cqi_dd_new = put(cqi_dd, binary_flag.);
drop cqi_dd segment;
run;
data myxls.cqi_dd ;
set temp_xxx (drop=_type_ _page_ _table_ rename=(segment_new = segment cqi_dd_new = cqi_dd) where=(segment ne '' and cqi_dd ne ''));
run;
data temp_xxx;
length segment_new $25 cqi_bp_new $ 25;
set cqi_bp_results;
segment_new = put(segment, segfmt.);
cqi_bp_new = put(cqi_bp, binary_flag.);
drop cqi_bp segment;
run;
data myxls.cqi_bp ;
set temp_xxx (drop=_type_ _page_ _table_ rename=(segment_new = segment cqi_bp_new = cqi_bp) where=(segment ne '' and cqi_bp ne ''));
run;
data temp_xxx;
length segment_new $25 cqi_web_new $ 25;
set cqi_web_results;
segment_new = put(segment, segfmt.);
cqi_web_new = put(cqi_web, binary_flag.);
drop cqi_web segment;
run;
data myxls.cqi_web ;
set temp_xxx (drop=_type_ _page_ _table_ rename=(segment_new = segment cqi_web_new = cqi_web) where=(segment ne '' and cqi_web ne ''));
run;
data temp_xxx;
length segment_new $25 cqi_deb_new $ 25;
set cqi_deb_results;
segment_new = put(segment, segfmt.);
cqi_deb_new = put(cqi_deb, binary_flag.);
drop cqi_deb segment;
run;
data myxls.cqi_deb ;
set temp_xxx (drop=_type_ _page_ _table_ rename=(segment_new = segment cqi_deb_new = cqi_deb) where=(segment ne '' and cqi_deb ne ''));
run;
data temp_xxx;
length segment_new $25 cqi_odl_new $ 25;
set cqi_odl_results;
segment_new = put(segment, segfmt.);
cqi_odl_new = put(cqi_odl, binary_flag.);
drop cqi_odl segment;
run;
data myxls.cqi_odl ;
set temp_xxx (drop=_type_ _page_ _table_ rename=(segment_new = segment cqi_odl_new = cqi_odl) where=(segment ne '' and cqi_odl ne ''));
run;
data temp_xxx;
length segment_new $25 rm_new $ 25;
set rm_results;
segment_new = put(segment, segfmt.);
rm_new = put(rm, $rmfmt.);
drop rm segment;
run;
data myxls.rm ;
set temp_xxx (drop=_type_ _page_ _table_ rename=(segment_new = segment rm_new = rm) where=(segment ne '' and rm ne ''));
run;
data temp_xxx;
length segment_new $25;
set tran3;
segment_new = put(segment, segfmt.);
drop segment;
run;
data myxls.chk_Trans;
set temp_xxx ( rename=(segment_new = segment) where=(segment ne ''));
run;
data temp_xxx;
length segment_new $25;
set web3;
segment_new = put(segment, segfmt.);
drop segment;
run;
data myxls.web_trans;
set temp_xxx (rename=(segment_new = segment) where=(segment ne ''));
run;
libname myxls clear;
