data temp_table;
set branch.bb_opp_data;
run;
data branch.bb_opp_data;
set branch.bb_opp_data;
hh_scaled = round(hh * weight,1);
dda_scaled = round(dda * weight,1);
dda_amt_scaled = round(dda_amt * weight,1);
DDA_con_scaled = round(DDA_con * weight,1);
mms_scaled = round(mms * weight,1);
mms_amt_scaled = round(mms_amt * weight,1);
MMS_con_scaled = round(MMS_con * weight,1);
sav_scaled = round(sav * weight,1);
sav_amt_scaled = round(sav_amt * weight,1);
sav_con_scaled = round(sav_con * weight,1);
tda_scaled = round(tda * weight,1);
tda_amt_scaled = round(tda_amt * weight,1);
TDA_con_scaled = round(TDA_con * weight,1);
cln_scaled = round(cln * weight,1);
cln_amt_scaled = round(cln_amt * weight,1);
CLN_con_scaled = round(CLN_con * weight,1);
boloc_scaled = round(boloc * weight,1);
boloc_amt_scaled = round(boloc_amt * weight,1);
BOLoc_con_scaled = round(BOLoc_con * weight,1);
baloc_scaled = round(baloc * weight,1);
baloc_amt_scaled = round(baloc_amt * weight,1);
BALOC_con_scaled = round(BALOC_con * weight,1);
cls_scaled = round(cls * weight,1);
cls_amt_scaled = round(cls_amt * weight,1);
CLS_con_scaled = round(CLS_con * weight,1);
wbb_scaled = round(wbb * weight,1);
deb_scaled = round(deb * weight,1);
RM_scaled = round(RM * weight,1);
con_scaled = round(con * weight,1);
run;
