%let d1=sas.sanmao;
%let d2=sas.sanmao;
%let c1=y(12);
%let c2=y(1,12);
%let b1=y;
%let b2=y;
%let p1=5 6 8 11;
%let p2=6 7 9 12;
%let q1=(12);
%let q2=(1,12);

%macro arima(method);
%do i=1 %to 2;
data f&i;
set &&d&i;
run;
%let k=1;
%let n=%scan(&&p&i,&k);
%do %while(&n ne);
proc arima data=f&i;
title "arima &&d&i var=&&c&i p=&n q=&&q&i method=&method";
identify var=&&c&i nlag=24;
estimate p=&n q=&&q&i method=&method plot;
forecast id=date out=out interval=year lead=12;
run;
proc gplot data=out;
plot &&b&i*date=1 forecast*date=2 l95*date=3 u95*date=3 /overlay;
symbol1 v=dot i=none c=black;
symbol2 v=plus i=join c=black;
symbol3 v=none i=join c=ligr;
run;
proc print data=out;
run;
 %let k=%eval(&k+1);
 %let n=%scan(&&p&i,&k);
%end;
%end;
%mend;

%arima(ml);

